### ISSUE TITLE
Refactor branding assets

### ISSUE THREAD

**Issue by yalozhkin** [iterative/static#10]
Added 2 boards on Branding:
* Master shapes [board](https://www.figma.com/file/IZDmco7kjAu8FknxTJOCxB/Logos-and-icons?node-id=1%3A2) – stores the original shapes of brand icons, types (e.g. iterative) and logotypes with guidelines; update once there is a new brand or changes to existing ones;
* Export assets [board](https://www.figma.com/file/IZDmco7kjAu8FknxTJOCxB/Logos-and-icons?node-id=515%3A1084) – a collection of exportable assets of icons and logotypes for the `iterative/static` repository.

**Comment by shcheklein** [comment]
@yalozhkin @arcticbear please let's not do this, VS Code icon is not official, we can't use or distribute it.
